# Generated by Django 4.2 on 2026-03-04 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Số điện thoại')),
                ('facebook_link', models.URLField(blank=True, default='', max_length=500, verbose_name='Link Facebook')),
                ('zalo_link', models.URLField(blank=True, default='', max_length=500, verbose_name='Link Zalo')),
                ('student_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã số sinh viên')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Địa chỉ giao dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông tin người dùng',
                'verbose_name_plural': 'Thông tin người dùng',
            },
        ),
    ]
