# Generated by Django 4.2.8 on 2026-02-19 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã số sinh viên')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Link Facebook')),
                ('zalo_number', models.CharField(blank=True, max_length=20, verbose_name='Số Zalo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Giới thiệu bản thân')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ gặp giao dịch')),
                ('reputation_score', models.FloatField(default=0.0, verbose_name='Điểm uy tín')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Số lượt đánh giá')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
    ]
