# Generated by Django 4.2 on 2026-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='zalo_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zalo_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Zalo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_link',
            field=models.URLField(verbose_name='Link Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
    ]
