# Generated by Django 4.2 on 2026-02-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='contact_facebook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='book',
            name='contact_zalo',
        ),
        migrations.AddField(
            model_name='book',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_books', to=settings.AUTH_USER_MODEL, verbose_name='Người mua'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('message', models.TextField(blank=True, help_text='Tin nhắn gửi kèm yêu cầu', verbose_name='Tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='books.book', verbose_name='Sách')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Yêu cầu mua sách',
                'verbose_name_plural': 'Danh sách yêu cầu mua sách',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'buyer')},
            },
        ),
    ]
