# Generated by Django 4.2 on 2026-03-11 08:16

import books.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tên sách')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Giá bán (VNĐ)')),
                ('condition', models.CharField(choices=[('new', 'Mới 100%'), ('like_new', 'Mới 95-99%'), ('good', 'Khá (80-94%)'), ('fair', 'Trung bình (60-79%)'), ('poor', 'Cũ (<60%)')], default='good', max_length=20, verbose_name='Tình trạng sách')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm (gạch bớt, đánh dấu, v.v.)', verbose_name='Ghi chú')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=books.models.get_book_image_upload_path, verbose_name='Ảnh bìa')),
                ('status', models.CharField(choices=[('available', 'Đang bán'), ('sold', 'Đã bán'), ('reserved', 'Đang giữ')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_books', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_for_sale', to=settings.AUTH_USER_MODEL, verbose_name='Người bán')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Danh sách sách',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên môn học')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Danh sách môn học',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=books.models.get_book_image_upload_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book')),
            ],
            options={
                'verbose_name': 'Ảnh sách',
                'verbose_name_plural': 'Danh sách ảnh',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.subject', verbose_name='Môn học'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='books_book_status_ea5e47_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['created_at'], name='books_book_created_572b47_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['price'], name='books_book_price_9cc12f_idx'),
        ),
    ]
