# Generated by Django 4.2.29 on 2026-03-25 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('message', models.TextField(blank=True, default='', help_text='Lời nhắn gửi đến người bán', verbose_name='Lời nhắn')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='books.book', verbose_name='Sách')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người bán')),
            ],
            options={
                'verbose_name': 'Yêu cầu mua sách',
                'verbose_name_plural': 'Danh sách yêu cầu mua sách',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='books_purch_status_667355_idx'), models.Index(fields=['created_at'], name='books_purch_created_f8aa4e_idx')],
            },
        ),
    ]
